name: Tests
on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  release:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Jest Run
        run: npm run test
